// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: internal/application/adapter/grpc/v1/proto/course.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetCategoryByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByCourseIdRequest) Reset() {
	*x = GetCategoryByCourseIdRequest{}
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByCourseIdRequest) ProtoMessage() {}

func (x *GetCategoryByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescGZIP(), []int{3}
}

func (x *GetCategoryByCourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

var File_internal_application_adapter_grpc_v1_proto_course_proto protoreflect.FileDescriptor

const file_internal_application_adapter_grpc_v1_proto_course_proto_rawDesc = "" +
	"\n" +
	"7internal/application/adapter/grpc/v1/proto/course.proto\x12\x02pb\"e\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"b\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"<\n" +
	"\x10CategoryResponse\x12(\n" +
	"\bcategory\x18\x01 \x01(\v2\f.pb.CategoryR\bcategory\";\n" +
	"\x1cGetCategoryByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId2\xa9\x01\n" +
	"\x0fCategoryService\x12C\n" +
	"\x0eCreateCategory\x12\x19.pb.CreateCategoryRequest\x1a\x14.pb.CategoryResponse\"\x00\x12Q\n" +
	"\x15GetCategoryByCourseId\x12 .pb.GetCategoryByCourseIdRequest\x1a\x14.pb.CategoryResponse\"\x00B\tZ\agrpc/pbb\x06proto3"

var (
	file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescOnce sync.Once
	file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescData []byte
)

func file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescGZIP() []byte {
	file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescOnce.Do(func() {
		file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_application_adapter_grpc_v1_proto_course_proto_rawDesc), len(file_internal_application_adapter_grpc_v1_proto_course_proto_rawDesc)))
	})
	return file_internal_application_adapter_grpc_v1_proto_course_proto_rawDescData
}

var file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_application_adapter_grpc_v1_proto_course_proto_goTypes = []any{
	(*Category)(nil),                     // 0: pb.Category
	(*CreateCategoryRequest)(nil),        // 1: pb.CreateCategoryRequest
	(*CategoryResponse)(nil),             // 2: pb.CategoryResponse
	(*GetCategoryByCourseIdRequest)(nil), // 3: pb.GetCategoryByCourseIdRequest
}
var file_internal_application_adapter_grpc_v1_proto_course_proto_depIdxs = []int32{
	0, // 0: pb.CategoryResponse.category:type_name -> pb.Category
	1, // 1: pb.CategoryService.CreateCategory:input_type -> pb.CreateCategoryRequest
	3, // 2: pb.CategoryService.GetCategoryByCourseId:input_type -> pb.GetCategoryByCourseIdRequest
	2, // 3: pb.CategoryService.CreateCategory:output_type -> pb.CategoryResponse
	2, // 4: pb.CategoryService.GetCategoryByCourseId:output_type -> pb.CategoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_application_adapter_grpc_v1_proto_course_proto_init() }
func file_internal_application_adapter_grpc_v1_proto_course_proto_init() {
	if File_internal_application_adapter_grpc_v1_proto_course_proto != nil {
		return
	}
	file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[0].OneofWrappers = []any{}
	file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_application_adapter_grpc_v1_proto_course_proto_rawDesc), len(file_internal_application_adapter_grpc_v1_proto_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_application_adapter_grpc_v1_proto_course_proto_goTypes,
		DependencyIndexes: file_internal_application_adapter_grpc_v1_proto_course_proto_depIdxs,
		MessageInfos:      file_internal_application_adapter_grpc_v1_proto_course_proto_msgTypes,
	}.Build()
	File_internal_application_adapter_grpc_v1_proto_course_proto = out.File
	file_internal_application_adapter_grpc_v1_proto_course_proto_goTypes = nil
	file_internal_application_adapter_grpc_v1_proto_course_proto_depIdxs = nil
}
