// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Define as mutations disponíveis na API para criação ou modificação de dados.
type Mutation struct {
}

// Input para a criação de uma nova categoria.
type NewCategory struct {
	// Nome da nova categoria.
	Name string `json:"name"`
	// Descrição opcional para a nova categoria.
	Description *string `json:"description,omitempty"`
}

// Input para a criação de um novo curso.
type NewCourse struct {
	// Nome do novo curso.
	Name string `json:"name"`
	// Descrição opcional para o novo curso.
	Description *string `json:"description,omitempty"`
	// O ID da categoria à qual o curso será associado.
	CategoryID string `json:"categoryId"`
}

// Define as queries disponíveis na API para consulta de dados.
type Query struct {
}
